// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: tic_tac_toe_proto/tic_tac_toe.proto

package tic_tac_toe_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  *int32 `protobuf:"varint,1,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Player *int32 `protobuf:"varint,2,opt,name=player,proto3,oneof" json:"player,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetState() int32 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Record) GetPlayer() int32 {
	if x != nil && x.Player != nil {
		return *x.Player
	}
	return 0
}

type Records struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordList []*Record `protobuf:"bytes,1,rep,name=recordList,proto3" json:"recordList,omitempty"`
}

func (x *Records) Reset() {
	*x = Records{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Records) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Records) ProtoMessage() {}

func (x *Records) ProtoReflect() protoreflect.Message {
	mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Records.ProtoReflect.Descriptor instead.
func (*Records) Descriptor() ([]byte, []int) {
	return file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescGZIP(), []int{1}
}

func (x *Records) GetRecordList() []*Record {
	if x != nil {
		return x.RecordList
	}
	return nil
}

type PlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XIndex int32 `protobuf:"varint,1,opt,name=x_index,json=xIndex,proto3" json:"x_index,omitempty"`
	YIndex int32 `protobuf:"varint,2,opt,name=y_index,json=yIndex,proto3" json:"y_index,omitempty"`
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerMove) GetXIndex() int32 {
	if x != nil {
		return x.XIndex
	}
	return 0
}

func (x *PlayerMove) GetYIndex() int32 {
	if x != nil {
		return x.YIndex
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board []string `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	State int32    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Turn  int32    `protobuf:"varint,3,opt,name=turn,proto3" json:"turn,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescGZIP(), []int{3}
}

func (x *GameState) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *GameState) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

var File_tic_tac_toe_proto_tic_tac_toe_proto protoreflect.FileDescriptor

var file_tic_tac_toe_proto_tic_tac_toe_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74,
	0x6f, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x55, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x33, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f,
	0x74, 0x6f, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x78, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a,
	0x07, 0x79, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4b, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x75, 0x72, 0x6e, 0x32, 0xbf, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x39,
	0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63,
	0x5f, 0x74, 0x6f, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e,
	0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e,
	0x74, 0x69, 0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x2e, 0x2f, 0x74, 0x69, 0x63, 0x5f, 0x74,
	0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x3b, 0x74, 0x69,
	0x63, 0x5f, 0x74, 0x61, 0x63, 0x5f, 0x74, 0x6f, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescOnce sync.Once
	file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescData = file_tic_tac_toe_proto_tic_tac_toe_proto_rawDesc
)

func file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescGZIP() []byte {
	file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescOnce.Do(func() {
		file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescData = protoimpl.X.CompressGZIP(file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescData)
	})
	return file_tic_tac_toe_proto_tic_tac_toe_proto_rawDescData
}

var file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tic_tac_toe_proto_tic_tac_toe_proto_goTypes = []interface{}{
	(*Record)(nil),        // 0: tic_tac_toe.Record
	(*Records)(nil),       // 1: tic_tac_toe.Records
	(*PlayerMove)(nil),    // 2: tic_tac_toe.PlayerMove
	(*GameState)(nil),     // 3: tic_tac_toe.GameState
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_tic_tac_toe_proto_tic_tac_toe_proto_depIdxs = []int32{
	0, // 0: tic_tac_toe.Records.recordList:type_name -> tic_tac_toe.Record
	2, // 1: tic_tac_toe.Player.Play:input_type -> tic_tac_toe.PlayerMove
	4, // 2: tic_tac_toe.Player.GetBoard:input_type -> google.protobuf.Empty
	4, // 3: tic_tac_toe.Player.GetRecords:input_type -> google.protobuf.Empty
	4, // 4: tic_tac_toe.Player.Play:output_type -> google.protobuf.Empty
	3, // 5: tic_tac_toe.Player.GetBoard:output_type -> tic_tac_toe.GameState
	1, // 6: tic_tac_toe.Player.GetRecords:output_type -> tic_tac_toe.Records
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tic_tac_toe_proto_tic_tac_toe_proto_init() }
func file_tic_tac_toe_proto_tic_tac_toe_proto_init() {
	if File_tic_tac_toe_proto_tic_tac_toe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Records); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tic_tac_toe_proto_tic_tac_toe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tic_tac_toe_proto_tic_tac_toe_proto_goTypes,
		DependencyIndexes: file_tic_tac_toe_proto_tic_tac_toe_proto_depIdxs,
		MessageInfos:      file_tic_tac_toe_proto_tic_tac_toe_proto_msgTypes,
	}.Build()
	File_tic_tac_toe_proto_tic_tac_toe_proto = out.File
	file_tic_tac_toe_proto_tic_tac_toe_proto_rawDesc = nil
	file_tic_tac_toe_proto_tic_tac_toe_proto_goTypes = nil
	file_tic_tac_toe_proto_tic_tac_toe_proto_depIdxs = nil
}
